inputs:
  inputDir: '../datasets/uci_sequences/inertial_signals/body_acc_x'
  trainFileName: 'body_acc_x_TRAIN'
  testFileName: 'body_acc_x_TEST'
  metricName: 'body_acc_x'
  metricMin: -1.0
  metricMax: 1.0

outputs:
  outputDir: 'traces'

params:
  chunkSize: 10
  runSanity: False
