inputs:
  inputDir: '../datasets/uci_sequences/debug/body_acc_x'
  trainFileName: 'body_acc_x_TRAIN' 
  testFileName: 'body_acc_x_TEST'
  metricName: None
  metricMin: -1.0
  metricMax: 1.0

outputs:
  outputDir: 'traces_debug'

params:
  chunkSize: 10
  runSanity: False


